#!/usr/bin/python
name = input("What's your name? ")
print "Nice to meet you " + name + "."
age=input("How old are you? ")
total = (2017-age)+100
print name + ", you'll be 100 years old in year " + str(total) +  "."
