#!/usr/bin/python
a = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
print ("The original list was " + str(a) + "." + '\n' + "the even number from that list are: " + str([num for num in a if num % 2 == 0]) + ".")
