#!/usr/bin/python

import requests
from bs4 import BeautifulSoup

file = input("File to save to: ")
 
base_url = 'http://www.nytimes.com'
r = requests.get(base_url)
soup = BeautifulSoup(r.text, "lxml")
 
with open(file, 'w') as open_file:
	for story_heading in soup.find_all(class_="story-heading"): 
    		if story_heading.a: 
       			 open_file.write(story_heading.a.text.replace("\n", " ").encode('utf-8').strip())
    		else: 
			 open_file.write(story_heading.contents[0].encode('utf-8').strip())

